version: "3.7"
services:
  senselink:
    container_name: senselink
    image: theta142/senselink:latest
    restart: unless-stopped
    network_mode: host
      
    # Optional environment variables
    # environment:
      # - LOGLEVEL=DEBUG
      # - SENSE_RESPONSE=False
      
    # Pass local configuration as volume to expected location
    volumes:
      - ./config.yml:/etc/senselink/config.yml:ro
