
name: Docker Test Builder

on:
  # Allow manual dispatch
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get tags
      run: git fetch --tags origin

    - name: Get git tag version
      run: echo git_tag=$(git describe --tags $(git rev-list --tags --max-count=1)) >> $GITHUB_ENV

    - name: Running for git tag
      run: echo ${{ env.git_tag }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: Build and push for tag ONLY if beta or alpha tagged
      if: ${{ contains(env.git_tag, 'beta') || contains(env.git_tag, 'alpha') }}
      run: docker build -t theta142/senselink:${{ env.git_tag }} --push .
