
name: Docker Image Builder for SenseLink

on:
  # Allow manual dispatch
  workflow_dispatch:
  # Run only manually for now
#  release:
#    types: [published, released]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Create builder
      run: docker buildx create --name senselink-builder
    - name: Use senselink-builder
      run: docker buildx use senselink-builder
    - run: docker buildx inspect --bootstrap
    - name: Define latest version via tag
      run: echo latest=$(git describe --tags $(git rev-list --tags --max-count=1))
#     - name: Define latest version via tag
#       run: echo latest=$(git describe --tags $(git rev-list --tags --max-count=1)) >> $GITHUB_ENV
#     - name: Log in to Docker Hub
#       uses: docker/login-action@v1.14.1
#       with:
#         username: theta142
#         password: ${{ secrets.DOCKER_HUB_TOKEN }}
#     - name: Build SenseLink for various platforms
#       run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t theta142/senselink:${{ env.latest }} -t theta142/senselink:latest --push .
