# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to PyPI

on:
  # Allow manual dispatch
  workflow_dispatch:
  release:
    types: [published, released]

jobs:
  pypi-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Get git tag version
      run: echo git_tag=$(git describe --tags $(git rev-list --tags --max-count=1)) >> $GITHUB_ENV

    - name: Get PyPI package version
      run: echo pypi_version=$(python3 setup.py -V) >> $GITHUB_ENV

    - name: Check for consistent versions
      if: ${{ env.git_tag != env.pypi_version }}
      run: |
        echo Git Tag ${{ env.git_tag }} does not match PyPI version ${{ env.pypi_version }}. Canceling workflow.
        exit 1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      # Double check that versions match
      if: ${{ env.git_tag == env.pypi_version }}
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
